version: '3.9'

services:

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: on-failure
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      -  "./postgres_data:/var/lib/postgresql/data"
    networks:
      - mynet

  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - mynet

  sport-game-app:
    container_name: sport-game-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${API_DEBUG_PORT}:9229"
    volumes:
      - "./:/app"
      - "/app/node_modules"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  postgres_data:
